"""Immutable printable HTML confirmations held in private, integrity-checked storage."""
import io
import logging
from html import escape
from uuid import uuid4

from fastapi import HTTPException
from sqlalchemy import select
from sqlalchemy.exc import SQLAlchemyError

from app.core.config import settings
from app.modules.authentication.security import utcnow
from app.modules.communications.common import ScopedService, transactional
from app.modules.communications.models import OfficialDocument
from app.modules.communications.schemas import DocumentOut
from app.modules.complaints.models import Complaint
from app.modules.dockets.models import Docket
from app.modules.evidence.storage import EvidenceStorage
from app.modules.refusals.models import ComplaintDecision, RefusalReason
from app.modules.stations.models import Station
from app.modules.system.service import allocate_document_number


class DocumentStorage(EvidenceStorage):
    def __init__(self):
        self.root = settings.document_storage_path.resolve()
        self.max_bytes = 1024 * 1024


def render_confirmation(number, kind, complaint, docket, now, reason=None):
    fields = [('Document number', number), ('Complaint reference', complaint.reference_number),
        ('Issued at (UTC)', now.isoformat())]
    if docket:
        fields.append(('CAS number', docket.cas_number))
    if reason:
        fields.append(('Refusal reason', reason))
    if kind == 'CASE_CLOSURE_CONFIRMATION':
        fields.append(('Closed at', docket.closed_at.isoformat()))
    title = kind.replace('_', ' ').title()
    rows = ''.join(f'<dt>{escape(label)}</dt><dd>{escape(str(value))}</dd>' for label, value in fields)
    return (f'<!doctype html><html lang="en"><meta charset="utf-8"><title>{escape(title)}</title>'
        '<style>body{font:16px Arial,sans-serif;max-width:760px;margin:48px auto;padding:24px;'
        'line-height:1.6}dt{font-weight:bold;margin-top:16px}dd{margin:0;overflow-wrap:anywhere}'
        '@media print{body{margin:0}}</style>'
        f'<h1>{escape(title)}</h1><dl>{rows}</dl>'
        '<p>Generated by the SAPS case docket academic prototype.</p></html>').encode('utf-8')


class DocumentService(ScopedService):
    @transactional
    def list(self, user, complaint_id, limit, offset):
        complaint = self.complaint_scope(user, complaint_id)
        rows = self.db.scalars(select(OfficialDocument).where(OfficialDocument.complaint_id == complaint.id)
            .order_by(OfficialDocument.generated_at.desc(), OfficialDocument.id.desc()).limit(limit).offset(offset))
        result = [DocumentOut.model_validate(row) for row in rows]
        self.audit(user, 'document.list', 'complaint', complaint.id, complaint.station_id)
        return result

    def generate(self, user, complaint_id, data):
        # Keep a saved file on ambiguous commit failure; reconciliation can remove
        # an orphan, whereas deleting a possibly committed document loses history.
        key, committing = None, False
        storage = DocumentStorage()
        try:
            result, key = self._generate(user, complaint_id, data, storage)
            committing = True
            self.db.commit()
            return result
        except Exception as exc:
            self.db.rollback()
            if key and not committing:
                storage.discard(key)
            if isinstance(exc, SQLAlchemyError):
                raise HTTPException(503, 'Document service unavailable') from None
            raise

    def _generate(self, user, complaint_id, data, storage):
        complaint = self.complaint_scope(user, complaint_id)
        # Serialize retries without a new uniqueness constraint or migration.
        self.db.scalar(select(Complaint).where(Complaint.id == complaint.id).with_for_update())
        docket = self.db.scalar(select(Docket).where(Docket.complaint_id == complaint.id))
        kind, reason = data.document_type, None
        if kind == 'REFUSAL_CONFIRMATION':
            decision = self.db.scalar(select(ComplaintDecision).where(ComplaintDecision.complaint_id == complaint.id)
                .order_by(ComplaintDecision.decision_sequence.desc()).limit(1))
            if decision is None or decision.decision != 'REFUSED':
                raise HTTPException(409, 'The latest decision is not a refusal')
            reason = self.db.get(RefusalReason, decision.refusal_reason_id).name
        if kind in {'DOCKET_REGISTRATION_CONFIRMATION', 'CASE_CLOSURE_CONFIRMATION'} and docket is None:
            raise HTTPException(409, 'No docket exists')
        if kind == 'CASE_CLOSURE_CONFIRMATION' and (docket.status not in {'CLOSED', 'ARCHIVED'} or not docket.closed_at):
            raise HTTPException(409, 'The case is not closed')
        existing = self.db.scalar(select(OfficialDocument).where(OfficialDocument.complaint_id == complaint.id,
            OfficialDocument.document_type == kind).order_by(OfficialDocument.generated_at.desc()).limit(1))
        if existing:
            self.audit(user, 'document.retrieve', 'official_document', existing.id, complaint.station_id)
            return DocumentOut.model_validate(existing), None
        station = self.db.get(Station, complaint.station_id)
        now = utcnow()
        number = allocate_document_number(self.db, station, now)
        content = render_confirmation(number, kind, complaint, docket, now, reason)
        key, size, digest = storage.save(io.BytesIO(content))
        try:
            row = OfficialDocument(id=uuid4(), complaint_id=complaint.id,
                docket_id=docket.id if docket else None, document_type=kind, document_number=number,
                storage_key=key, media_type='text/html', file_size_bytes=size, sha256_hash=digest,
                generated_by_user_id=user.id, generated_at=now)
            self.db.add(row)
            self.db.flush()
            self.audit(user, 'document.generate', 'official_document', row.id, complaint.station_id)
            return DocumentOut.model_validate(row), key
        except Exception:
            try:
                storage.discard(key)
            except OSError:
                logging.getLogger(__name__).error('Document cleanup requires reconciliation')
            raise

    @transactional
    def download(self, user, document_id):
        self.require(user, 'confirmation.download')
        row = self.db.get(OfficialDocument, document_id)
        if row is None:
            raise HTTPException(404, 'Document not found')
        complaint_id = row.complaint_id
        if complaint_id is None:
            docket = self.db.get(Docket, row.docket_id)
            if docket is None:
                raise HTTPException(404, 'Document not found')
            complaint_id = docket.complaint_id
        complaint = self.complaint_scope(user, complaint_id)
        if row.docket_id:
            docket = self.db.get(Docket, row.docket_id)
            if docket is None or docket.complaint_id != complaint.id:
                raise HTTPException(409, 'Document parent mismatch')
        content = DocumentStorage().read_verified(row)
        self.audit(user, 'document.download', 'official_document', row.id, complaint.station_id)
        return content, row.id
