"""add authentication sessions and totp mfa

Revision ID: 089c746ed6a9
Revises: 1edbbd1f3330
Create Date: 2026-09-22 10:07:39.950968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '089c746ed6a9'
down_revision: Union[str, Sequence[str], None] = '1edbbd1f3330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Repeat the preflight under a write-blocking lock to close the race between
    # inspection and index creation. Never merge/delete conflicting accounts.
    op.execute('LOCK TABLE case_mgmt.users IN SHARE ROW EXCLUSIVE MODE')
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM case_mgmt.users GROUP BY lower(username) HAVING count(*) > 1)
               OR EXISTS (SELECT 1 FROM case_mgmt.users GROUP BY lower(email) HAVING count(*) > 1) THEN
                RAISE EXCEPTION 'Case-insensitive username/email conflicts exist; migration stopped';
            END IF;
        END $$
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_session_id', sa.UUID(), nullable=True),
    sa.Column('created_from_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("refresh_token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_auth_sessions_refresh_hash')),
    sa.CheckConstraint('expires_at > issued_at', name=op.f('ck_auth_sessions_expiration')),
    sa.CheckConstraint('replaced_by_session_id IS NULL OR replaced_by_session_id <> id', name=op.f('ck_auth_sessions_not_self_replacing')),
    sa.ForeignKeyConstraint(['replaced_by_session_id'], ['case_mgmt.auth_sessions.id'], name=op.f('fk_auth_sessions_replaced_by_session_id_auth_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['case_mgmt.users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True, schema='case_mgmt')
    op.create_index(op.f('ix_auth_sessions_revoked_at'), 'auth_sessions', ['revoked_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False, schema='case_mgmt')
    op.create_table('user_mfa_methods',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('method_type', sa.String(length=20), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method_type = 'TOTP'", name=op.f('ck_user_mfa_methods_method_type')),
    sa.CheckConstraint('NOT is_active OR verified_at IS NOT NULL', name=op.f('ck_user_mfa_methods_active_verified')),
    sa.ForeignKeyConstraint(['user_id'], ['case_mgmt.users.id'], name=op.f('fk_user_mfa_methods_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_mfa_methods')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_user_mfa_methods_user_id'), 'user_mfa_methods', ['user_id'], unique=False, schema='case_mgmt')
    op.create_index('uq_user_mfa_methods_active_totp', 'user_mfa_methods', ['user_id'], unique=True, schema='case_mgmt', postgresql_where=sa.text("is_active AND method_type = 'TOTP'"))
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True, schema='case_mgmt')
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True, schema='case_mgmt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_username_lower', table_name='users', schema='case_mgmt')
    op.drop_index('uq_users_email_lower', table_name='users', schema='case_mgmt')
    op.drop_index('uq_user_mfa_methods_active_totp', table_name='user_mfa_methods', schema='case_mgmt', postgresql_where=sa.text("is_active AND method_type = 'TOTP'"))
    op.drop_index(op.f('ix_user_mfa_methods_user_id'), table_name='user_mfa_methods', schema='case_mgmt')
    op.drop_table('user_mfa_methods', schema='case_mgmt')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions', schema='case_mgmt')
    op.drop_index(op.f('ix_auth_sessions_revoked_at'), table_name='auth_sessions', schema='case_mgmt')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions', schema='case_mgmt')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions', schema='case_mgmt')
    op.drop_table('auth_sessions', schema='case_mgmt')
    # ### end Alembic commands ###
