"""complete rbac mappings and identifier counters

Revision ID: 1edbbd1f3330
Revises: a59515a63a4d
Create Date: 2026-09-22 01:38:03.297930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1edbbd1f3330'
down_revision: Union[str, Sequence[str], None] = 'a59515a63a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ROLE_PERMISSIONS = {
    'COMPLAINANT': 'complaint.submit complaint.view_own case.track_own confirmation.download',
    'CHARGE_OFFICER': 'complaint.register complaint.view_station complaint.decide refusal.record confirmation.download',
    'STATION_COMMANDER': 'complaint.view_station refusal.escalation.view docket.approve docket.assign audit.view_station dashboard.view_station alert.view confirmation.download',
    'INVESTIGATING_OFFICER': 'docket.view_assigned case.update_status case.add_note case.close evidence.manage evidence.view_custody feedback.provide confirmation.download',
    'SYSTEM_ADMINISTRATOR': 'user.manage role.manage permission.manage station.manage audit.view_all dashboard.view_all alert.view',
    'SAPS_MANAGEMENT': 'audit.view_all dashboard.view_all alert.view',
    'NCC_OFFICER': 'refusal.escalation.view dashboard.view_all alert.view',
}


def seed_role_permissions():
    # Capture RETURNING pairs in a migration-owned rollback function. This durable
    # provenance avoids deleting pre-existing grants on downgrade and does not
    # overload granted_at or add an application-facing bookkeeping table.
    pairs = ', '.join(
        f"('{role}', '{permission}')"
        for role, permissions in ROLE_PERMISSIONS.items() for permission in permissions.split()
    )
    op.execute(f"""
        DO $seed$
        DECLARE inserted_pairs text;
        BEGIN
            IF EXISTS (
                SELECT 1 FROM (VALUES {pairs}) AS requested(role_code, permission_code)
                LEFT JOIN case_mgmt.roles r ON r.code = requested.role_code
                LEFT JOIN case_mgmt.permissions p ON p.code = requested.permission_code
                WHERE r.id IS NULL OR p.id IS NULL
            ) THEN
                RAISE EXCEPTION 'Required RBAC role or permission seed is missing';
            END IF;
            WITH inserted AS (
                INSERT INTO case_mgmt.role_permissions (role_id, permission_id)
                SELECT r.id, p.id FROM (VALUES {pairs}) AS requested(role_code, permission_code)
                JOIN case_mgmt.roles r ON r.code = requested.role_code
                JOIN case_mgmt.permissions p ON p.code = requested.permission_code
                ON CONFLICT (role_id, permission_id) DO NOTHING
                RETURNING role_id, permission_id
            )
            SELECT string_agg(format('(%L::uuid, %L::uuid)', role_id, permission_id), ', ')
                INTO inserted_pairs FROM inserted;
            EXECUTE format(
                'CREATE FUNCTION case_mgmt.undo_rbac_seed_1edbbd1f3330() RETURNS void LANGUAGE sql AS %L',
                'DELETE FROM case_mgmt.role_permissions WHERE ' ||
                CASE WHEN inserted_pairs IS NULL THEN 'false'
                     ELSE '(role_id, permission_id) IN (' || inserted_pairs || ')' END
            );
        END $seed$
    """)
    op.execute('REVOKE ALL ON FUNCTION case_mgmt.undo_rbac_seed_1edbbd1f3330() FROM PUBLIC, saps_api')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identifier_counters',
    sa.Column('counter_type', sa.String(length=20), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("counter_type IN ('COMPLAINT', 'CAS', 'EVIDENCE', 'DOCUMENT')", name=op.f('ck_identifier_counters_counter_type')),
    sa.CheckConstraint('calendar_year >= 2000', name=op.f('ck_identifier_counters_calendar_year')),
    sa.CheckConstraint('last_value >= 0', name=op.f('ck_identifier_counters_last_value')),
    sa.ForeignKeyConstraint(['station_id'], ['case_mgmt.stations.id'], name=op.f('fk_identifier_counters_station_id_stations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('counter_type', 'station_id', 'calendar_year', name=op.f('pk_identifier_counters')),
    schema='case_mgmt'
    )
    op.create_index('ix_identifier_counters_station_year', 'identifier_counters', ['station_id', 'calendar_year'], unique=False, schema='case_mgmt')
    op.execute('GRANT SELECT, INSERT, UPDATE ON case_mgmt.identifier_counters TO saps_api')
    seed_role_permissions()


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('SELECT case_mgmt.undo_rbac_seed_1edbbd1f3330()')
    op.execute('DROP FUNCTION case_mgmt.undo_rbac_seed_1edbbd1f3330()')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_identifier_counters_station_year', table_name='identifier_counters', schema='case_mgmt')
    op.drop_table('identifier_counters', schema='case_mgmt')
    # ### end Alembic commands ###
