"""create communications alerts and audit tables

Revision ID: a59515a63a4d
Revises: fd1a582b8271
Create Date: 2026-09-22 01:01:19.421360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a59515a63a4d'
down_revision: Union[str, Sequence[str], None] = 'fd1a582b8271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


APPEND_ONLY_TABLES = (
    'complaint_decisions', 'docket_approvals', 'docket_status_history',
    'investigation_notes', 'evidence_files', 'evidence_custody_events',
    'case_feedback', 'official_documents', 'notification_attempts', 'audit_logs',
)
# These four existing tables had UPDATE/DELETE before this revision. Earlier
# migrations already removed them from complaint_decisions/docket_approvals.
RESTORE_WRITABLE_TABLES = (
    'docket_status_history', 'investigation_notes', 'evidence_files', 'evidence_custody_events',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('database_user', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("actor_type <> 'USER' OR actor_user_id IS NOT NULL", name=op.f('ck_audit_logs_user_actor_required')),
    sa.CheckConstraint("actor_type IN ('USER', 'SYSTEM', 'DATABASE')", name=op.f('ck_audit_logs_actor_type')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['case_mgmt.users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['case_mgmt.stations.id'], name=op.f('fk_audit_logs_station_id_stations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False, schema='case_mgmt')
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_audit_logs_station_id'), 'audit_logs', ['station_id'], unique=False, schema='case_mgmt')
    op.create_table('alerts',
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('docket_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alert_type = 'SYSTEM_COMPLIANCE' OR complaint_id IS NOT NULL OR docket_id IS NOT NULL", name=op.f('ck_alerts_parent_required')),
    sa.CheckConstraint("alert_type IN ('NON_COMPLIANT_REFUSAL', 'OVERDUE_DOCKET', 'CASE_INACTIVITY', 'UNACKNOWLEDGED_ESCALATION', 'EVIDENCE_CUSTODY_EXCEPTION', 'SYSTEM_COMPLIANCE')", name=op.f('ck_alerts_alert_type')),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_alerts_severity')),
    sa.CheckConstraint("status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')", name=op.f('ck_alerts_status')),
    sa.CheckConstraint('acknowledged_at IS NULL OR acknowledged_by_user_id IS NOT NULL', name=op.f('ck_alerts_acknowledgment_actor')),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_by_user_id IS NOT NULL', name=op.f('ck_alerts_resolution_actor')),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['case_mgmt.users.id'], name=op.f('fk_alerts_acknowledged_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['case_mgmt.users.id'], name=op.f('fk_alerts_assigned_to_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complaint_id'], ['case_mgmt.complaints.id'], name=op.f('fk_alerts_complaint_id_complaints'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docket_id'], ['case_mgmt.dockets.id'], name=op.f('fk_alerts_docket_id_dockets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['case_mgmt.users.id'], name=op.f('fk_alerts_resolved_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['case_mgmt.stations.id'], name=op.f('fk_alerts_station_id_stations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_alerts_detected_at'), 'alerts', ['detected_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_alerts_due_at'), 'alerts', ['due_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_alerts_station_id'), 'alerts', ['station_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False, schema='case_mgmt')
    op.create_table('case_feedback',
    sa.Column('docket_id', sa.UUID(), nullable=False),
    sa.Column('complainant_id', sa.UUID(), nullable=False),
    sa.Column('provided_by_officer_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_official', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supersedes_feedback_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("feedback_type IN ('REGISTRATION', 'PROGRESS_UPDATE', 'REQUEST_FOR_INFORMATION', 'REFUSAL', 'CASE_CLOSURE', 'GENERAL')", name=op.f('ck_case_feedback_feedback_type')),
    sa.CheckConstraint('supersedes_feedback_id IS NULL OR supersedes_feedback_id <> id', name=op.f('ck_case_feedback_not_self_superseding')),
    sa.ForeignKeyConstraint(['complainant_id'], ['case_mgmt.complainants.id'], name=op.f('fk_case_feedback_complainant_id_complainants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docket_id'], ['case_mgmt.dockets.id'], name=op.f('fk_case_feedback_docket_id_dockets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provided_by_officer_id'], ['case_mgmt.officers.id'], name=op.f('fk_case_feedback_provided_by_officer_id_officers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_feedback_id'], ['case_mgmt.case_feedback.id'], name=op.f('fk_case_feedback_supersedes_feedback_id_case_feedback'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_feedback')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_case_feedback_complainant_id'), 'case_feedback', ['complainant_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_case_feedback_docket_id'), 'case_feedback', ['docket_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_case_feedback_feedback_type'), 'case_feedback', ['feedback_type'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_case_feedback_published_at'), 'case_feedback', ['published_at'], unique=False, schema='case_mgmt')
    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_complainant_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('docket_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('destination_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('SMS', 'EMAIL', 'IN_APP')", name=op.f('ck_notifications_channel')),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'SENT', 'DELIVERED', 'FAILED', 'CANCELLED')", name=op.f('ck_notifications_status')),
    sa.CheckConstraint('(recipient_user_id IS NOT NULL) <> (recipient_complainant_id IS NOT NULL)', name=op.f('ck_notifications_exactly_one_recipient')),
    sa.ForeignKeyConstraint(['complaint_id'], ['case_mgmt.complaints.id'], name=op.f('fk_notifications_complaint_id_complaints'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docket_id'], ['case_mgmt.dockets.id'], name=op.f('fk_notifications_docket_id_dockets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_complainant_id'], ['case_mgmt.complainants.id'], name=op.f('fk_notifications_recipient_complainant_id_complainants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['case_mgmt.users.id'], name=op.f('fk_notifications_recipient_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False, schema='case_mgmt')
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_notifications_recipient_complainant_id'), 'notifications', ['recipient_complainant_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False, schema='case_mgmt')
    op.create_table('official_documents',
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('docket_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("document_type IN ('COMPLAINT_REGISTRATION_CONFIRMATION', 'REFUSAL_CONFIRMATION', 'DOCKET_REGISTRATION_CONFIRMATION', 'CASE_CLOSURE_CONFIRMATION')", name=op.f('ck_official_documents_document_type')),
    sa.CheckConstraint("length(btrim(storage_key)) > 0 AND storage_key !~ '^[[:space:]]*([A-Za-z][A-Za-z0-9+.-]*:|/)' AND left(ltrim(storage_key), 1) <> chr(92)", name=op.f('ck_official_documents_storage_key')),
    sa.CheckConstraint("sha256_hash ~ '^[0-9A-Fa-f]{64}$'", name=op.f('ck_official_documents_sha256_hash')),
    sa.CheckConstraint('complaint_id IS NOT NULL OR docket_id IS NOT NULL', name=op.f('ck_official_documents_parent_required')),
    sa.CheckConstraint('file_size_bytes > 0', name=op.f('ck_official_documents_positive_size')),
    sa.ForeignKeyConstraint(['complaint_id'], ['case_mgmt.complaints.id'], name=op.f('fk_official_documents_complaint_id_complaints'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docket_id'], ['case_mgmt.dockets.id'], name=op.f('fk_official_documents_docket_id_dockets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['case_mgmt.users.id'], name=op.f('fk_official_documents_generated_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_official_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_official_documents_storage_key')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_official_documents_complaint_id'), 'official_documents', ['complaint_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_official_documents_docket_id'), 'official_documents', ['docket_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_official_documents_document_number'), 'official_documents', ['document_number'], unique=True, schema='case_mgmt')
    op.create_index(op.f('ix_official_documents_document_type'), 'official_documents', ['document_type'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_official_documents_generated_at'), 'official_documents', ['generated_at'], unique=False, schema='case_mgmt')
    op.create_table('notification_attempts',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("outcome IN ('SENT', 'FAILED', 'REJECTED', 'TIMEOUT')", name=op.f('ck_notification_attempts_outcome')),
    sa.CheckConstraint('attempt_number > 0', name=op.f('ck_notification_attempts_positive_attempt')),
    sa.ForeignKeyConstraint(['notification_id'], ['case_mgmt.notifications.id'], name=op.f('fk_notification_attempts_notification_id_notifications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_attempts')),
    sa.UniqueConstraint('notification_id', 'attempt_number', name=op.f('uq_notification_attempts_notification_id')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_notification_attempts_attempted_at'), 'notification_attempts', ['attempted_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_notification_attempts_notification_id'), 'notification_attempts', ['notification_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_notification_attempts_outcome'), 'notification_attempts', ['outcome'], unique=False, schema='case_mgmt')
    op.execute("""
        CREATE FUNCTION case_mgmt.reject_append_only_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only; UPDATE and DELETE are not permitted',
                TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME
                USING ERRCODE = '55000';
        END $$
    """)
    for table in APPEND_ONLY_TABLES:
        # Alphabetical ordering makes this run before existing UPDATE validators.
        op.execute(f"CREATE TRIGGER aa_append_only BEFORE UPDATE OR DELETE ON case_mgmt.{table} "
                   "FOR EACH ROW EXECUTE FUNCTION case_mgmt.reject_append_only_mutation()")
        op.execute(f"GRANT SELECT, INSERT ON case_mgmt.{table} TO saps_api")
        op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON case_mgmt.{table} FROM saps_api")


def downgrade() -> None:
    """Downgrade schema."""
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER aa_append_only ON case_mgmt.{table}")
    op.execute("DROP FUNCTION case_mgmt.reject_append_only_mutation()")
    for table in RESTORE_WRITABLE_TABLES:
        op.execute(f"GRANT UPDATE, DELETE ON case_mgmt.{table} TO saps_api")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_attempts_outcome'), table_name='notification_attempts', schema='case_mgmt')
    op.drop_index(op.f('ix_notification_attempts_notification_id'), table_name='notification_attempts', schema='case_mgmt')
    op.drop_index(op.f('ix_notification_attempts_attempted_at'), table_name='notification_attempts', schema='case_mgmt')
    op.drop_table('notification_attempts', schema='case_mgmt')
    op.drop_index(op.f('ix_official_documents_generated_at'), table_name='official_documents', schema='case_mgmt')
    op.drop_index(op.f('ix_official_documents_document_type'), table_name='official_documents', schema='case_mgmt')
    op.drop_index(op.f('ix_official_documents_document_number'), table_name='official_documents', schema='case_mgmt')
    op.drop_index(op.f('ix_official_documents_docket_id'), table_name='official_documents', schema='case_mgmt')
    op.drop_index(op.f('ix_official_documents_complaint_id'), table_name='official_documents', schema='case_mgmt')
    op.drop_table('official_documents', schema='case_mgmt')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications', schema='case_mgmt')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications', schema='case_mgmt')
    op.drop_index(op.f('ix_notifications_recipient_complainant_id'), table_name='notifications', schema='case_mgmt')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications', schema='case_mgmt')
    op.drop_index('ix_notifications_created_at', table_name='notifications', schema='case_mgmt')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications', schema='case_mgmt')
    op.drop_table('notifications', schema='case_mgmt')
    op.drop_index(op.f('ix_case_feedback_published_at'), table_name='case_feedback', schema='case_mgmt')
    op.drop_index(op.f('ix_case_feedback_feedback_type'), table_name='case_feedback', schema='case_mgmt')
    op.drop_index(op.f('ix_case_feedback_docket_id'), table_name='case_feedback', schema='case_mgmt')
    op.drop_index(op.f('ix_case_feedback_complainant_id'), table_name='case_feedback', schema='case_mgmt')
    op.drop_table('case_feedback', schema='case_mgmt')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts', schema='case_mgmt')
    op.drop_index(op.f('ix_alerts_station_id'), table_name='alerts', schema='case_mgmt')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts', schema='case_mgmt')
    op.drop_index(op.f('ix_alerts_due_at'), table_name='alerts', schema='case_mgmt')
    op.drop_index(op.f('ix_alerts_detected_at'), table_name='alerts', schema='case_mgmt')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts', schema='case_mgmt')
    op.drop_table('alerts', schema='case_mgmt')
    op.drop_index(op.f('ix_audit_logs_station_id'), table_name='audit_logs', schema='case_mgmt')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs', schema='case_mgmt')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs', schema='case_mgmt')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs', schema='case_mgmt')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs', schema='case_mgmt')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs', schema='case_mgmt')
    op.drop_table('audit_logs', schema='case_mgmt')
    # ### end Alembic commands ###
