"""add complaint uploads vehicle details and password recovery

Revision ID: aea1947e1d7f
Revises: e712ac340a01
Create Date: 2026-09-28 20:33:54.375712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea1947e1d7f'
down_revision: Union[str, Sequence[str], None] = 'e712ac340a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['case_mgmt.users.id'], name=op.f('fk_password_resets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_resets_token_hash')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False, schema='case_mgmt')
    op.create_table('complaint_uploads',
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=150), nullable=False),
    sa.Column('storage_key', sa.String(length=32), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("purpose IN ('EVIDENCE', 'VEHICLE_REGISTRATION')", name=op.f('ck_complaint_uploads_purpose')),
    sa.CheckConstraint('file_size_bytes > 0', name=op.f('ck_complaint_uploads_positive_size')),
    sa.ForeignKeyConstraint(['complaint_id'], ['case_mgmt.complaints.id'], name=op.f('fk_complaint_uploads_complaint_id_complaints'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['case_mgmt.users.id'], name=op.f('fk_complaint_uploads_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_uploads')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_complaint_uploads_storage_key')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_complaint_uploads_complaint_id'), 'complaint_uploads', ['complaint_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_complaint_uploads_uploaded_by_user_id'), 'complaint_uploads', ['uploaded_by_user_id'], unique=False, schema='case_mgmt')
    op.add_column('complaints', sa.Column('vehicle_number_plate', sa.String(length=30), nullable=True), schema='case_mgmt')
    op.execute('GRANT SELECT, INSERT, UPDATE ON case_mgmt.password_resets, case_mgmt.complaint_uploads TO saps_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'vehicle_number_plate', schema='case_mgmt')
    op.drop_index(op.f('ix_complaint_uploads_uploaded_by_user_id'), table_name='complaint_uploads', schema='case_mgmt')
    op.drop_index(op.f('ix_complaint_uploads_complaint_id'), table_name='complaint_uploads', schema='case_mgmt')
    op.drop_table('complaint_uploads', schema='case_mgmt')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets', schema='case_mgmt')
    op.drop_table('password_resets', schema='case_mgmt')
    # ### end Alembic commands ###
