"""add verified walkin account consent

Revision ID: b360beaef541
Revises: d44d391e2a43
Create Date: 2026-09-27 18:06:59.945454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b360beaef541'
down_revision: Union[str, Sequence[str], None] = 'd44d391e2a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_email_consents',
    sa.Column('officer_user_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('complainant_id', sa.UUID(), nullable=True),
    sa.Column('email_digest', sa.String(length=64), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_state', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['complainant_id'], ['case_mgmt.complainants.id'], name=op.f('fk_intake_email_consents_complainant_id_complainants')),
    sa.ForeignKeyConstraint(['officer_user_id'], ['case_mgmt.users.id'], name=op.f('fk_intake_email_consents_officer_user_id_users')),
    sa.ForeignKeyConstraint(['station_id'], ['case_mgmt.stations.id'], name=op.f('fk_intake_email_consents_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_email_consents')),
    schema='case_mgmt'
    )
    op.execute('GRANT SELECT, INSERT, UPDATE ON case_mgmt.intake_email_consents TO saps_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intake_email_consents', schema='case_mgmt')
    # ### end Alembic commands ###
