"""track multipart SMS receipt completion

Revision ID: c80f15010548
Revises: dc4056c454ca
Create Date: 2026-09-26 23:57:05.318876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c80f15010548'
down_revision: Union[str, Sequence[str], None] = 'dc4056c454ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_intents', sa.Column('provider_message_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False), schema='case_mgmt')
    op.add_column('sms_intents', sa.Column('delivery_receipts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False), schema='case_mgmt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_intents', 'delivery_receipts', schema='case_mgmt')
    op.drop_column('sms_intents', 'provider_message_ids', schema='case_mgmt')
    # ### end Alembic commands ###
