"""add case email outbox and reference challenges

Revision ID: d44d391e2a43
Revises: c80f15010548
Create Date: 2026-09-27 12:24:28.263582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44d391e2a43'
down_revision: Union[str, Sequence[str], None] = 'c80f15010548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_tracking_rate_limits',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_email_tracking_rate_limits')),
    schema='case_mgmt'
    )
    op.create_table('email_tracking_challenges',
    sa.Column('complainant_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('email_digest', sa.String(length=64), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_state', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['complainant_id'], ['case_mgmt.complainants.id'], name=op.f('fk_email_tracking_challenges_complainant_id_complainants')),
    sa.ForeignKeyConstraint(['complaint_id'], ['case_mgmt.complaints.id'], name=op.f('fk_email_tracking_challenges_complaint_id_complaints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_tracking_challenges')),
    schema='case_mgmt'
    )
    op.create_table('case_email_intents',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('email_digest', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['case_mgmt.notifications.id'], name=op.f('fk_case_email_intents_notification_id_notifications')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_case_email_intents')),
    sa.UniqueConstraint('event_key', name=op.f('uq_case_email_intents_event_key')),
    schema='case_mgmt'
    )
    op.execute('GRANT SELECT, INSERT, UPDATE ON case_mgmt.case_email_intents, case_mgmt.email_tracking_challenges, case_mgmt.email_tracking_rate_limits TO saps_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_email_intents', schema='case_mgmt')
    op.drop_table('email_tracking_challenges', schema='case_mgmt')
    op.drop_table('email_tracking_rate_limits', schema='case_mgmt')
    # ### end Alembic commands ###
