"""add SMS phone proof challenges and outbox

Revision ID: dc4056c454ca
Revises: eabef524c593
Create Date: 2026-09-26 23:37:06.836458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4056c454ca'
down_revision: Union[str, Sequence[str], None] = 'eabef524c593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_rate_limits',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_sms_rate_limits')),
    schema='case_mgmt'
    )
    op.create_table('sms_phone_proofs',
    sa.Column('complainant_id', sa.UUID(), nullable=False),
    sa.Column('phone_digest', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complainant_id'], ['case_mgmt.complainants.id'], name=op.f('fk_sms_phone_proofs_complainant_id_complainants')),
    sa.PrimaryKeyConstraint('complainant_id', name=op.f('pk_sms_phone_proofs')),
    schema='case_mgmt'
    )
    op.create_table('sms_challenges',
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('complainant_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('phone_digest', sa.String(length=64), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_state', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['case_mgmt.users.id'], name=op.f('fk_sms_challenges_actor_user_id_users')),
    sa.ForeignKeyConstraint(['complainant_id'], ['case_mgmt.complainants.id'], name=op.f('fk_sms_challenges_complainant_id_complainants')),
    sa.ForeignKeyConstraint(['complaint_id'], ['case_mgmt.complaints.id'], name=op.f('fk_sms_challenges_complaint_id_complaints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_challenges')),
    schema='case_mgmt'
    )
    op.create_table('sms_intents',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('phone_digest', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['case_mgmt.notifications.id'], name=op.f('fk_sms_intents_notification_id_notifications')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_sms_intents')),
    sa.UniqueConstraint('event_key', name=op.f('uq_sms_intents_event_key')),
    schema='case_mgmt'
    )
    op.execute('GRANT SELECT, INSERT, UPDATE ON case_mgmt.sms_phone_proofs, case_mgmt.sms_challenges, case_mgmt.sms_rate_limits, case_mgmt.sms_intents TO saps_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_intents', schema='case_mgmt')
    op.drop_table('sms_challenges', schema='case_mgmt')
    op.drop_table('sms_phone_proofs', schema='case_mgmt')
    op.drop_table('sms_rate_limits', schema='case_mgmt')
    # ### end Alembic commands ###
