"""add explicit email authentication and code challenges

Revision ID: eabef524c593
Revises: 089c746ed6a9
Create Date: 2026-09-25 03:29:56.171373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabef524c593'
down_revision: Union[str, Sequence[str], None] = '089c746ed6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_auth',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verified_email', sa.String(length=254), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['case_mgmt.users.id'], name=op.f('fk_user_email_auth_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_email_auth')),
    schema='case_mgmt'
    )
    op.create_table('email_auth_challenges',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=254), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_state', sa.String(length=20), nullable=False),
    sa.CheckConstraint("code_digest ~ '^[0-9a-f]{64}$'", name=op.f('ck_email_auth_challenges_code_digest')),
    sa.CheckConstraint("delivery_state IN ('pending', 'accepted', 'failed')", name=op.f('ck_email_auth_challenges_delivery_state')),
    sa.CheckConstraint("purpose IN ('register', 'login', 'transition')", name=op.f('ck_email_auth_challenges_purpose')),
    sa.ForeignKeyConstraint(['session_id'], ['case_mgmt.auth_sessions.id'], name=op.f('fk_email_auth_challenges_session_id_auth_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['case_mgmt.users.id'], name=op.f('fk_email_auth_challenges_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_email_auth_challenges')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_email_auth_challenges_user_id'), 'email_auth_challenges', ['user_id'], unique=False, schema='case_mgmt')
    op.execute('GRANT SELECT, INSERT, UPDATE ON case_mgmt.user_email_auth, case_mgmt.email_auth_challenges TO saps_api')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_auth_challenges_user_id'), table_name='email_auth_challenges', schema='case_mgmt')
    op.drop_table('email_auth_challenges', schema='case_mgmt')
    op.drop_table('user_email_auth', schema='case_mgmt')
    # ### end Alembic commands ###
