"""create investigation and evidence tables

Revision ID: fd1a582b8271
Revises: 53b49290f8f4
Create Date: 2026-09-22 00:18:53.652229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1a582b8271'
down_revision: Union[str, Sequence[str], None] = '53b49290f8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_assignments',
    sa.Column('docket_id', sa.UUID(), nullable=False),
    sa.Column('investigating_officer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_officer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignment_reason', sa.Text(), nullable=True),
    sa.Column('unassignment_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('unassigned_at IS NULL OR unassigned_at >= assigned_at', name=op.f('ck_case_assignments_assignment_dates')),
    sa.ForeignKeyConstraint(['assigned_by_officer_id'], ['case_mgmt.officers.id'], name=op.f('fk_case_assignments_assigned_by_officer_id_officers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docket_id'], ['case_mgmt.dockets.id'], name=op.f('fk_case_assignments_docket_id_dockets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investigating_officer_id'], ['case_mgmt.officers.id'], name=op.f('fk_case_assignments_investigating_officer_id_officers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_assignments')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_case_assignments_assigned_at'), 'case_assignments', ['assigned_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_case_assignments_docket_id'), 'case_assignments', ['docket_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_case_assignments_investigating_officer_id'), 'case_assignments', ['investigating_officer_id'], unique=False, schema='case_mgmt')
    op.create_index('uq_case_assignments_active_docket', 'case_assignments', ['docket_id'], unique=True, schema='case_mgmt', postgresql_where=sa.text('unassigned_at IS NULL'))
    op.create_table('docket_status_history',
    sa.Column('docket_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("from_status IN ('PENDING_APPROVAL', 'APPROVED', 'ACTIVE', 'ON_HOLD', 'CLOSED', 'ARCHIVED')", name=op.f('ck_docket_status_history_from_status')),
    sa.CheckConstraint("to_status IN ('PENDING_APPROVAL', 'APPROVED', 'ACTIVE', 'ON_HOLD', 'CLOSED', 'ARCHIVED')", name=op.f('ck_docket_status_history_to_status')),
    sa.CheckConstraint('from_status IS NULL OR from_status <> to_status', name=op.f('ck_docket_status_history_status_changed')),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['case_mgmt.users.id'], name=op.f('fk_docket_status_history_changed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docket_id'], ['case_mgmt.dockets.id'], name=op.f('fk_docket_status_history_docket_id_dockets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docket_status_history')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_docket_status_history_changed_at'), 'docket_status_history', ['changed_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_docket_status_history_docket_id'), 'docket_status_history', ['docket_id'], unique=False, schema='case_mgmt')
    op.create_index('uq_docket_status_history_initial', 'docket_status_history', ['docket_id'], unique=True, schema='case_mgmt', postgresql_where=sa.text('from_status IS NULL'))
    op.create_table('evidence_items',
    sa.Column('docket_id', sa.UUID(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('is_digital', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_by_officer_id', sa.UUID(), nullable=True),
    sa.Column('collection_location', sa.Text(), nullable=True),
    sa.Column('registered_by_user_id', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'REGISTERED'"), nullable=False),
    sa.Column('current_custodian_officer_id', sa.UUID(), nullable=True),
    sa.Column('current_storage_location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('DOCUMENT', 'IMAGE', 'VIDEO', 'AUDIO', 'PHYSICAL_OBJECT', 'DIGITAL_DEVICE', 'OTHER')", name=op.f('ck_evidence_items_evidence_type')),
    sa.CheckConstraint("status IN ('REGISTERED', 'IN_CUSTODY', 'TRANSFERRED', 'UNDER_ANALYSIS', 'RELEASED', 'DISPOSED')", name=op.f('ck_evidence_items_status')),
    sa.ForeignKeyConstraint(['collected_by_officer_id'], ['case_mgmt.officers.id'], name=op.f('fk_evidence_items_collected_by_officer_id_officers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_custodian_officer_id'], ['case_mgmt.officers.id'], name=op.f('fk_evidence_items_current_custodian_officer_id_officers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docket_id'], ['case_mgmt.dockets.id'], name=op.f('fk_evidence_items_docket_id_dockets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['case_mgmt.users.id'], name=op.f('fk_evidence_items_registered_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_evidence_items_docket_id'), 'evidence_items', ['docket_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_items_evidence_reference'), 'evidence_items', ['evidence_reference'], unique=True, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_items_evidence_type'), 'evidence_items', ['evidence_type'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_items_registered_at'), 'evidence_items', ['registered_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_items_status'), 'evidence_items', ['status'], unique=False, schema='case_mgmt')
    op.create_table('investigation_notes',
    sa.Column('docket_id', sa.UUID(), nullable=False),
    sa.Column('author_officer_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("note_type IN ('GENERAL', 'PROGRESS', 'LEAD', 'INTERVIEW', 'FORENSIC', 'ADMINISTRATIVE', 'CORRECTION')", name=op.f('ck_investigation_notes_note_type')),
    sa.ForeignKeyConstraint(['author_officer_id'], ['case_mgmt.officers.id'], name=op.f('fk_investigation_notes_author_officer_id_officers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['docket_id'], ['case_mgmt.dockets.id'], name=op.f('fk_investigation_notes_docket_id_dockets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_notes')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_investigation_notes_author_officer_id'), 'investigation_notes', ['author_officer_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_investigation_notes_created_at'), 'investigation_notes', ['created_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_investigation_notes_docket_id'), 'investigation_notes', ['docket_id'], unique=False, schema='case_mgmt')
    op.create_table('evidence_custody_events',
    sa.Column('evidence_item_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('from_custodian_officer_id', sa.UUID(), nullable=True),
    sa.Column('to_custodian_officer_id', sa.UUID(), nullable=True),
    sa.Column('from_location', sa.String(length=255), nullable=True),
    sa.Column('to_location', sa.String(length=255), nullable=True),
    sa.Column('event_notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("event_type IN ('REGISTERED', 'COLLECTED', 'RECEIVED', 'TRANSFERRED', 'ACCESSED', 'ANALYSIS_STARTED', 'ANALYSIS_COMPLETED', 'RELEASED', 'DISPOSED')", name=op.f('ck_evidence_custody_events_event_type')),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['case_mgmt.evidence_items.id'], name=op.f('fk_evidence_custody_events_evidence_item_id_evidence_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_custodian_officer_id'], ['case_mgmt.officers.id'], name=op.f('fk_evidence_custody_events_from_custodian_officer_id_officers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['case_mgmt.users.id'], name=op.f('fk_evidence_custody_events_performed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_custodian_officer_id'], ['case_mgmt.officers.id'], name=op.f('fk_evidence_custody_events_to_custodian_officer_id_officers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_custody_events')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_evidence_custody_events_event_type'), 'evidence_custody_events', ['event_type'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_custody_events_evidence_item_id'), 'evidence_custody_events', ['evidence_item_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_custody_events_occurred_at'), 'evidence_custody_events', ['occurred_at'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_custody_events_performed_by_user_id'), 'evidence_custody_events', ['performed_by_user_id'], unique=False, schema='case_mgmt')
    op.create_table('evidence_files',
    sa.Column('evidence_item_id', sa.UUID(), nullable=False),
    sa.Column('file_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("length(btrim(storage_key)) > 0 AND storage_key !~ '^[[:space:]]*([A-Za-z][A-Za-z0-9+.-]*:|/)' AND left(ltrim(storage_key), 1) <> chr(92)", name=op.f('ck_evidence_files_storage_key')),
    sa.CheckConstraint("sha256_hash ~ '^[0-9A-Fa-f]{64}$'", name=op.f('ck_evidence_files_sha256_hash')),
    sa.CheckConstraint('file_size_bytes > 0', name=op.f('ck_evidence_files_positive_size')),
    sa.CheckConstraint('file_version > 0', name=op.f('ck_evidence_files_positive_version')),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['case_mgmt.evidence_items.id'], name=op.f('fk_evidence_files_evidence_item_id_evidence_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['case_mgmt.users.id'], name=op.f('fk_evidence_files_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_files')),
    sa.UniqueConstraint('evidence_item_id', 'file_version', name=op.f('uq_evidence_files_evidence_item_id')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_evidence_files_storage_key')),
    schema='case_mgmt'
    )
    op.create_index(op.f('ix_evidence_files_evidence_item_id'), 'evidence_files', ['evidence_item_id'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_files_sha256_hash'), 'evidence_files', ['sha256_hash'], unique=False, schema='case_mgmt')
    op.create_index(op.f('ix_evidence_files_uploaded_at'), 'evidence_files', ['uploaded_at'], unique=False, schema='case_mgmt')
    # A partial index prevents duplicate initial records but cannot ensure that
    # the initial record is first. This is an integrity check, not an append-only
    # trigger: updates and deletes remain available until the audit phase.
    op.execute("""
        CREATE FUNCTION case_mgmt.validate_initial_docket_history() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE is_new_initial boolean;
        BEGIN
            PERFORM 1 FROM case_mgmt.dockets WHERE id = NEW.docket_id FOR UPDATE;
            is_new_initial := TG_OP = 'INSERT';
            IF TG_OP = 'UPDATE' THEN
                is_new_initial := OLD.from_status IS NOT NULL OR OLD.docket_id <> NEW.docket_id;
            END IF;
            IF NEW.from_status IS NULL AND EXISTS (
                SELECT 1 FROM case_mgmt.docket_status_history
                WHERE docket_id = NEW.docket_id AND id <> NEW.id
                  AND (is_new_initial OR changed_at < NEW.changed_at)
            ) THEN
                RAISE EXCEPTION 'Only the first status-history record may have a null from_status'
                  USING ERRCODE = '23514', CONSTRAINT = 'ck_docket_status_history_initial_record';
            END IF;
            IF NEW.from_status IS NOT NULL AND EXISTS (
                SELECT 1 FROM case_mgmt.docket_status_history
                WHERE docket_id = NEW.docket_id AND id <> NEW.id
                  AND from_status IS NULL AND changed_at > NEW.changed_at
            ) THEN
                RAISE EXCEPTION 'Status history cannot precede its initial record'
                  USING ERRCODE = '23514', CONSTRAINT = 'ck_docket_status_history_initial_record';
            END IF;
            RETURN NEW;
        END $$
    """)
    op.execute("""
        CREATE TRIGGER docket_history_initial_record
        BEFORE INSERT OR UPDATE ON case_mgmt.docket_status_history
        FOR EACH ROW EXECUTE FUNCTION case_mgmt.validate_initial_docket_history()
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_files_uploaded_at'), table_name='evidence_files', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_files_sha256_hash'), table_name='evidence_files', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_files_evidence_item_id'), table_name='evidence_files', schema='case_mgmt')
    op.drop_table('evidence_files', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_custody_events_performed_by_user_id'), table_name='evidence_custody_events', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_custody_events_occurred_at'), table_name='evidence_custody_events', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_custody_events_evidence_item_id'), table_name='evidence_custody_events', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_custody_events_event_type'), table_name='evidence_custody_events', schema='case_mgmt')
    op.drop_table('evidence_custody_events', schema='case_mgmt')
    op.drop_index(op.f('ix_investigation_notes_docket_id'), table_name='investigation_notes', schema='case_mgmt')
    op.drop_index(op.f('ix_investigation_notes_created_at'), table_name='investigation_notes', schema='case_mgmt')
    op.drop_index(op.f('ix_investigation_notes_author_officer_id'), table_name='investigation_notes', schema='case_mgmt')
    op.drop_table('investigation_notes', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_items_status'), table_name='evidence_items', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_items_registered_at'), table_name='evidence_items', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_items_evidence_type'), table_name='evidence_items', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_items_evidence_reference'), table_name='evidence_items', schema='case_mgmt')
    op.drop_index(op.f('ix_evidence_items_docket_id'), table_name='evidence_items', schema='case_mgmt')
    op.drop_table('evidence_items', schema='case_mgmt')
    op.drop_index('uq_docket_status_history_initial', table_name='docket_status_history', schema='case_mgmt', postgresql_where=sa.text('from_status IS NULL'))
    op.drop_index(op.f('ix_docket_status_history_docket_id'), table_name='docket_status_history', schema='case_mgmt')
    op.drop_index(op.f('ix_docket_status_history_changed_at'), table_name='docket_status_history', schema='case_mgmt')
    op.drop_table('docket_status_history', schema='case_mgmt')
    op.execute("DROP FUNCTION case_mgmt.validate_initial_docket_history()")
    op.drop_index('uq_case_assignments_active_docket', table_name='case_assignments', schema='case_mgmt', postgresql_where=sa.text('unassigned_at IS NULL'))
    op.drop_index(op.f('ix_case_assignments_investigating_officer_id'), table_name='case_assignments', schema='case_mgmt')
    op.drop_index(op.f('ix_case_assignments_docket_id'), table_name='case_assignments', schema='case_mgmt')
    op.drop_index(op.f('ix_case_assignments_assigned_at'), table_name='case_assignments', schema='case_mgmt')
    op.drop_table('case_assignments', schema='case_mgmt')
    # ### end Alembic commands ###
